const pick = require("lodash/pick");
const shipment = {
  "shipmentId": "SETDNOS20327",
  "workflowStatus": "pickupRequestByMerchant",
  "workflowStatusForUser": "Pending Pickup",
  "noOfParcels": "3",
  "deliveryRegion": "JHR",
  "parcelSize": "M",
  "oddSize": "1",
  "instructions": "place it at step door",
  "receiverName": "name 01",
  "receiverAddress": "ad01  46000 HN VN",
  "pickupStation": "TEST012",
  "intermediateStation": "",
  "deliveryStation": "DJY052",
  "currentHub": "",
  "nextHub": "",
  "currentOwner": "61a08b31fde6ac688f0e022c",
  "assignedDriver": "61a08b2dfde6ac5d160e0227",
  "pickupOperatorPhoneNumber": "",
  "assignedDriverPhoneNumber": "",
  "deliveryOperatorPhoneNumber": "",
  "merchant": "Name One",
  "merchantCode": "DNOS",
  "merchantUserId": "8b94c618-9464-4685-ae22-ec8cad64f1c5",
  "senderAddress": "Address 1 Address 2 68100 hunt Selangor",
  "senderPhoneNumber": "+60898989898",
  "merchantReferenceId": "to",
  "parcelWeight": "1.000",
  "parcelHeight": "0.00",
  "parcelWidth": "0.00",
  "parcelLength": "0.00",
  "receiverAddress1": "ad01",
  "receiverAddress2": "",
  "receiverPostalCode": "46000",
  "receiverCity": "HN",
  "receiverState": "VN",
  "receiverCountry": "",
  "receiverPhoneNumber": "+60987456321",
  "receiverEmail": "",
  "senderAddress1": "Address 1",
  "senderAddress2": "Address 2",
  "senderPostalCode": "68100",
  "senderCity": "hunt",
  "senderState": "Selangor",
  "senderCountry": "",
  "senderReceiverStationMmdKey": "",
  "receiverGoogleMaps": "https://maps.google.com/?q=ad01%20%2046000%20HN%20VN",
  "receiverWazeMaps": "https://waze.com/ul?q=ad01%20%2046000%20HN%20VN",
  "senderGoogleMaps": "https://maps.google.com/?q=Address%201%20Address%202%2068100%20hunt%20Selangor",
  "senderWazeMaps": "https://waze.com/ul?q=Address%201%20Address%202%2068100%20hunt%20Selangor",
  "deliveredAt": "0000-00-00 00:00:00",
  "lastFailedDeliveryAttemptDate": "0000-00-00 00:00:00",
  "lastStatusUpdatedAt": "2022-04-05 16:56:07",
  "createdBy": "merchantdashboard@testlogistika.com.my",
  "signature": "[]",
  "deliveredTo": "",
  "proofOfDelivery": "[]",
  "deliveryAddressType": "",
  "isFeedbackGiven": "0",
  "failedDeliveryAttempts": "0.00",
  "failedDeliveryReason": "",
  "originLocation": "PETRONAS Taman Daya",
  "destinationLocation": "PETRONAS Damansara Jaya 2",
  "currentLocation": "",
  "initialPickupType": "Pickup",
  "pickupVehicleType": "Half van",
  "deliveryOption": "Delivery",
  "estimatedDelivery": "",
  "trackingToken": "72MT60IGQLRALLWW",
  "shippingLabel": "",
  "qrCode": "to",
  "shippingProvider": "Logistika",
  "parcelSizeRemark": "",
  "isReverseShipmentCreated": "1",
  "parentShipmentId": "",
  "receiverLatitude": "",
  "receiverLongitude": "",
  "assignedLmdDriver": "",
  "priority": "0",
  "sequence": "0",
  "lmdEta": "",
  "run": "0",
  "plannedStatus": "",
  "planExceptionRemark": "",
  "blackoutTimeEnd": "",
  "vehicleType": "",
  "serviceType": "Standard delivery",
  "isReceiverOfficeAddress": "0",
  "planDate": "",
  "isLineHaul": "1",
  "merchantId": "",
  "itemValue": "1.00",
  "itemDescription": "pudo-itemDescription",
  "price": "0.00",
  "pickupAddress1": "Address 1",
  "pickupAddress2": "Address 2",
  "pickupCity": "hunt",
  "pickupState": "Selangor",
  "pickupCountry": "",
  "pickupPostalCode": "68100",
  "billingType": "Intrastate",
  "senderDeliveryRegion": null,
  "createdAt": "2022-04-05 16:56:01",
  "updatedAt": "2022-04-07 13:28:51",
  "shipmentRowId": "118011",
  "assignedDeliveryPartner": "TDY053 FMD Admin",
  "currentOwnerFullName": "Merchant Dashboard",
  "updatedBy": "Super Admin",
  "updatedByUserId": "61a08b32fde6aca51f0e022e",
  "bulkShipmentId": "624c041c1ff01d45520c3d0e",
  "bulkShipmentFileName": "file existing.xlsx"
}
const shipmentPayload = {
  "deliveryRegion": "JHR",
  "shippingProvider": "Logistika",
  "serviceType": "Standard delivery",
  "isLineHaul": "1",
  "isReverseShipmentCreated": "1",
  "billingType": "Intrastate",
  "instructions": "place it at step door 1",
  "noOfParcels": "1",
  "parcelSize": "M",
  "oddSize": "1",
  "parcelWeight": "1.1111111", 
  "itemDescription": "pudo-itemDescription",
  "itemValue": "1.00"
};

const deliveryPayLoad = {
  "pickupStation": "",
  "deliveryStation": "",
  "nextHub": "",
  "currentOwner": "",
  "assignedDeliveryPartner": "",
  "initialPickupType": "",
  "pickupVehicleType": "",
  "deliveryOption": "",
  "instructions": "",
  "estimatedDelivery": "",
  "failedDeliveryAttempt": "",
  "proofOfDelivery": "[]",
  "deliveredTo": "",
  "deliveryAddressType": ""
}

console.log(pick(shipment, Object.keys(shipmentPayload)));

// check audit logs, shipment history, ts.